{{- if or .Values.runnerRegistrationToken .Values.runnerToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gitlab-runner-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-gitlab-runner
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  runner-registration-token: {{ default "" .Values.runnerRegistrationToken | b64enc | quote }}
  runner-token: {{ default "" .Values.runnerToken | b64enc | quote }}
{{- end -}}
